### ISSUE TITLE
make error "undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)' "

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#284]
### system configuration
Operating system: Ubuntu 14.04
GPUs : NVIDIA GTX 1080 
Compiler: gcc 5.4
CUDA version: CUDA 8.0 
CUDNN version : cuDNN v5.1

### Problem
Whenever I compile caffe ssd branch on 3 different PCs, this error always occur. 
A weird thing is that compiling caffe origin was success.

I saw other issues which are solved by gcc 4.8 version.

So, When I tried to compile with gcc 4.8, json parser problem occured. Then I changed gcc version to gcc-5.0 version and solved the problem.

```
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/convert_annoset.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/ssd/ssd_detect.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
.build_release/tools/convert_imageset.o: In function `main':
convert_imageset.cpp:(.text.startup+0x16b6): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
convert_imageset.cpp:(.text.startup+0x19ae): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset.bin] Error 1
```

Are there people who solve the problems?

Thanks

**Comment by youngwanLEE** [comment]
solved it.

**Comment by gallupliu** [comment]
how to solve it ?thank you

**Comment by youngwanLEE** [comment]
@gallupliu the reason is wrong location of GPU slot. When I changed the GPU location to another slot, that problem was solved.

**Comment by gallupliu** [comment]
I have 1080<tel:1080>×2  slot?



发自我的小米手机
在 youngwanLEE <notifications@github.com>，2016年11月23日 下午3:57写道：

@gallupliu<https://github.com/gallupliu> the reason is wrong location of GPU slot. When I changed the GPU location to another slot, that problem was solved.
